version: '3.7'

services:
  app:
    build: .
    container_name: brain-agriculture-app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    restart: always
    env_file:
      - .env.development
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: brain-agriculture-db
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: